### ISSUE TITLE
Failed to synchronize

### ISSUE THREAD

**Issue by devtrap** [agiliumtrade-ai/metaapi-python-sdk#11]
Hi 
I'm not able to stream the stock price via example which exist in 
https://github.com/agiliumtrade-ai/metaapi-python-sdk/blob/master/examples/streamQuotes/streamQuotes.py

below error happened :
{'name': 'TimeoutException', 'message': 'Timed out waiting for MetaApi to synchronize to MetaTrader account 8644b0da-620e-4e59-b658-42d42a9dda55, synchronization id None', 'trace': 'Traceback (most recent call last):\n  File "streamQuotes.py", line 81, in stream_quotes\n    await connection.wait_synchronized()\n  File "/Users/mehrad/Library/Python/3.8/lib/python/site-packages/metaapi_cloud_sdk/metaApi/streamingMetaApiConnection.py", line 516, in wait_synchronized\n    raise TimeoutException(\'Timed out waiting for MetaApi to synchronize to MetaTrader account \' +\nmetaapi_cloud_sdk.clients.timeoutException.TimeoutException: Timed out waiting for MetaApi to synchronize to MetaTrader account 8644b0da-620e-4e59-b658-42d42a9dda55, synchronization id None\n'}
packet queue is empty, aborting

I thought synchronize ID was None and maybe that makes some problem but also it's not fixed after setting synchronize id using random function.

Would you please let me know if there is any problem with my configs ? Should I change my domain or sth else ?

here it's filled variables for mentioned example :

token = 'xxx'
account_id= '8644b0da-620e-4e59-b658-42d42a9dda55'
symbol= 'EURUSD'
domain='agiliumtrade.agiliumtrade.ai'

**Comment by RomanKisilenko** [comment]
Thank you for asking this question here.

I can see you have deployed your account in new-york region. By default python SDK 16.2.x connects to vint-hill. 

In order to connect to new-york region please pass corresponding options to MetaApi constructor:
https://github.com/agiliumtrade-ai/metaapi-python-sdk/blob/master/lib/metaApi/metaApi.py#L51-L52
﻿https://github.com/agiliumtrade-ai/metaapi-python-sdk/blob/master/lib/metaApi/metaApi.py#L87-L93
﻿
﻿Feel free to reopen the issue if this does not resolve your issue.

**Comment by Esatyilmaz0** [comment]
Hello, I'm trying to get price information for EURUSD, but terminal_state.price("EURUSD") is returning none, how can I fix this?

**Comment by RomanKisilenko** [comment]
> Hello, I'm trying to get price information for EURUSD, but terminal_state.price("EURUSD") is returning none, how can I fix this?

Please make sure to subscribe to market data of this symbol first. Also please make sure your broker indeed provides a symbol of this name.
