### ISSUE TITLE
Profit in history

### ISSUE THREAD

**Issue by ijustwant** [agiliumtrade-ai/metaapi-python-sdk#6]
Hi
I'm not able to read the profit value in closed orders. How can i do that?

**Comment by RomanKisilenko** [comment]
Hello, please retrieve historical deals in order to read the profit (get_deals_by_ticket, get_deals_by_position, get_deals_by_time_range methods). Historical orders contains only data related to how orders were filled and when. If you need to figure out how did balance change and breakdown of profit/commission/swap then you should use deals data. If you'll have further questions, please contact us via online chat, we will provide assistance to you.
